table fact_Colaboradores
	lineageTag: 7112ef34-680b-4ff9-b9d9-f1d1a7fb0686

	column COLABORADORES
		dataType: string
		lineageTag: b9b1b3cb-e2d6-48c8-80e4-3ba884b2a9df
		summarizeBy: none
		sourceColumn: COLABORADORES

		annotation SummarizationSetBy = Automatic

	column CARGO
		dataType: string
		lineageTag: 7fca0c80-c98f-49b8-9aa7-51207eb9755d
		summarizeBy: none
		sourceColumn: CARGO

		annotation SummarizationSetBy = Automatic

	column TIME
		dataType: string
		lineageTag: 83acd295-13d1-441c-b3bf-e8b90318ae2b
		summarizeBy: none
		sourceColumn: TIME

		annotation SummarizationSetBy = Automatic

	column DIRETORIA
		dataType: string
		lineageTag: d055d43f-2e91-472f-9aab-3cad8cb346e4
		summarizeBy: none
		sourceColumn: DIRETORIA

		annotation SummarizationSetBy = Automatic

	column 'SETOR-DEPARTAMENTO '
		dataType: string
		lineageTag: a4eb7640-b753-469d-b02e-4d2634211aa4
		summarizeBy: none
		sourceColumn: "SETOR-DEPARTAMENTO "

		annotation SummarizationSetBy = Automatic

	column UNIDADE
		dataType: string
		lineageTag: 9ae8e1cc-caeb-4b67-afe7-b3c41d761db6
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column 'CENTRO DE CUSTO'
		dataType: string
		lineageTag: dcde7cae-1960-4afd-98d2-4dfc731edb0d
		summarizeBy: none
		sourceColumn: CENTRO DE CUSTO

		annotation SummarizationSetBy = Automatic

	column MesAno
		dataType: dateTime
		formatString: Short Date
		lineageTag: e648a2e6-2f10-4e31-9bbf-98da8274bbe6
		summarizeBy: none
		sourceColumn: MesAno

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CPF
		dataType: string
		lineageTag: c7400fd0-f7e5-4b91-ba8b-4cb26823cd22
		summarizeBy: none
		sourceColumn: CPF

		annotation SummarizationSetBy = Automatic

	partition fact_Colaboradores = m
		mode: import
		source = ```
				let
				    Source = Folder.Contents( PastaLocal )
				    {[Name="fact_Colaboradores"]}[Content],
				
				    FiltrarArquivos = Table.SelectRows( Source, each Text.EndsWith( [Name], ".xls" ) ),
				
				    ColunasSelecionadas = FiltrarArquivos[ [Content], [Name] ],
				
				    // Função que trata cada aba da mesma tabela e unifica as informações
				    fxColaboradores = 
				        ( arquivo as binary, MesAno as text ) as table =>
				        let
				            Source = Excel.Workbook ( arquivo, true ),
				            AbaDesejada = Table.SelectRows( Source, each [Name] = "LISTA DE COLABORADORES" ),
				            Dados = AbaDesejada{0}[Data],
				            Promover = Table.PromoteHeaders( Dados, [PromoteAllScalars = true] ),
				            FiltrarNulos = Table.SelectRows( Promover, each ( [COLABORADORES] <> null ) ),
				
				            ColunasNecessarias = { 
				                "COLABORADORES", // Responsavel por exibir o nome
				                "CPF", // Relacionar com a dim_Colaboradores
				                "CARGO", // Cargo exercido pelo colaborador
				                "UNIDADE", // Unidade a que pertence. Necessária ? Tenho a informação na dim_Lojas
				                "DIRETORIA", // Necessária
				                "TIME", // Necessária
				                "SETOR-DEPARTAMENTO ", // Necessária
				                "CENTRO DE CUSTO" }, // Necessária
				
				            // Tipagem centralizada dos dados
				            DefinirTipagem =  {
				                    {"COLABORADORES", type text},
				                    {"CPF", type text},
				                    {"CARGO", type text}, 
				                    {"DIRETORIA", type text},
				                    {"TIME", type text}, 
				                    {"SETOR-DEPARTAMENTO ", type text}, 
				                    {"UNIDADE", type text}, 
				                    {"CENTRO DE CUSTO", type text}
				                },
				            SelecionarColunas = Table.SelectColumns( FiltrarNulos, ColunasNecessarias ),
				            
				            TiparColuna = Table.TransformColumnTypes( SelecionarColunas, DefinirTipagem ),
				            
				            NormalizarCPF = Table.TransformColumns( TiparColuna, { { "CPF", each Text.PadStart( Text.From(_), 11, "0" ), type text } } ),
				            
				            AdicionarColuna = Table.AddColumn( NormalizarCPF, "MesAno", each Date.FromText( Text.BetweenDelimiters( MesAno, " ", ".xls" ) ), type date )
				        in
				            AdicionarColuna,
				
				    
				    // Responsavel por chamar a função em cada planilha
				    ListaTabelas = Table.AddColumn(
				        ColunasSelecionadas,
				            "Tabelas", each 
				                fxColaboradores( 
				                    [Content], // Carrega todo conteudo
				                    [Name] // Adiciona a informação de MesAno
				                ), 
				            type table 
				        )
				        [Tabelas],
				
				    // Unir todas as planilhas tratadas pela função
				    CombinarTabelas = Table.Combine( ListaTabelas )
				in
				    CombinarTabelas
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

