table Medidas
	lineageTag: d29aad8c-b158-4c1f-bf5e-e4c4b1ea5853

	measure 'Qtd Funcionarios' = ```
			
			CALCULATE(
			    DISTINCTCOUNT(fact_Colaboradores[COLABORADORES])
			)
			
			```
		formatString: 0
		lineageTag: 720e92f7-45a4-425a-bccc-76a41c4312d9

	measure 'Eixo Y Diretoria' = ```
			
			VAR _Tabela = ALLSELECTED( fact_Colaboradores[DIRETORIA], fact_Colaboradores[DIRETORIA] )
			VAR _MaiorValor = MAXX( _Tabela, [Qtd Funcionarios] )
			VAR _Deslocamento = 1.2
			RETURN
			
			_MaiorValor * _Deslocamento 
			```
		lineageTag: cd4e2aaa-531a-4fdc-b109-0a356f00313b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Eixo Y Time' = ```
			
			VAR _Tabela = ALLSELECTED( fact_Colaboradores[TIME], fact_Colaboradores[TIME] )
			VAR _MaiorValor = MAXX( _Tabela, [Qtd Funcionarios] )
			VAR _Deslocamento = 1.2
			RETURN
			
			_MaiorValor * _Deslocamento 
			```
		lineageTag: 6d86633a-74f7-46d4-85d6-6d71cfb315b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Filtro Data Colaboradores' =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( fact_Colaboradores ),
			        FILTER (
			            fact_Colaboradores,
			            fact_Colaboradores[Data] =  MAX( dim_Calendario[Date] )
			        )
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 004f2b75-65c3-412c-a9f8-f65fd029889e

	measure 'Eixo Y SetorDepartamento' = ```
			
			VAR _Tabela = ALLSELECTED( fact_Colaboradores[SETOR-DEPARTAMENTO ], fact_Colaboradores[SETOR-DEPARTAMENTO ] )
			VAR _MaiorValor = MAXX( _Tabela, [Qtd Funcionarios] )
			VAR _Deslocamento = 1.2
			RETURN
			
			_MaiorValor * _Deslocamento 
			```
		lineageTag: 34bbe294-27d1-44bb-b478-9fa1372d8521

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SaldoHoras =
			
			VAR TotalMinutos = SUM( fact_BancoHoras[Saldo Minutos] )
			VAR Horas = QUOTIENT( TotalMinutos, 60 )
			VAR Minutos = TotalMinutos - ( Horas * 60 )
			VAR Resultado =
			    Horas * 100
			    + ABS( Minutos ) * SIGN( TotalMinutos )
			RETURN
			Resultado
		formatString: 00:00
		lineageTag: 1a85dd09-5b3e-4619-9e69-eba5a98e3cfc

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Titulo Dinamico Grafico HE' =
			
			VAR _SelecaoEixo = SELECTEDVALUE(aux_SlicerX[NomeCampo])
			VAR _SelecaoHoras = SELECTEDVALUE(aux_SlicerY[NomeCampo] )
			VAR _Texto = "Distribuição de HE por "
			VAR _TextoPela = " - Devidas Pela Empresa"
			VAR _TextoPelo = " - Devidas Pelo Colaborador"
			
			RETURN
			_Texto & IF( _SelecaoEixo = "Colaborador", "Colaborador", "Centro de Custo" ) & IF( _SelecaoHoras = "Colaborador", _TextoPelo, _TextoPela )
		lineageTag: aba58217-0978-4a6a-9c20-9856a1f6e2a7

	measure 'SaldoHoras Devido Colaborador' = ```
			
			VAR TotalMinutos = CALCULATE( SUM( fact_BancoHoras[Saldo Minutos] ), fact_BancoHoras[Saldo Minutos] < 0 ) 
			VAR Horas = QUOTIENT( TotalMinutos, 60 )
			VAR Minutos = TotalMinutos - ( Horas * 60 )
			VAR Resultado =
			    Horas * 100
			    + ABS( Minutos ) * SIGN( TotalMinutos )
			RETURN
			ABS ( Resultado )
			```
		formatString: 00:00
		lineageTag: 847cff21-4a9f-4063-914a-7f71b611c0ab

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'SaldoHoras Devido Empresa' = ```
			
			VAR TotalMinutos = CALCULATE( SUM( fact_BancoHoras[Saldo Minutos] ), fact_BancoHoras[Saldo Minutos] > 0 ) 
			VAR Horas = QUOTIENT( TotalMinutos, 60 )
			VAR Minutos = TotalMinutos - ( Horas * 60 )
			VAR Resultado =
			    Horas * 100
			    + ABS( Minutos ) * SIGN( TotalMinutos )
			RETURN
			Resultado
			```
		formatString: 00:00
		lineageTag: 149acdf3-d2af-4458-a534-fbcdf60d980b

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Eixo Y Saldo Horas' = ```
			
			VAR _Tabela = ALLSELECTED( fact_BancoHoras[Data Saldo], fact_BancoHoras[Data Saldo] )
			VAR _MaxEmpresa = MAXX( _Tabela, [SaldoHoras Devido Empresa] )
			VAR _MaxColaborador = MAXX( _Tabela, [SaldoHoras Devido Colaborador] )
			VAR _MaiorValor = MAX( _MaxEmpresa, _MaxColaborador )
			VAR _Deslocamento = 1.3
			RETURN
			_MaiorValor * _Deslocamento 
			```
		lineageTag: 0b6770f8-224d-4923-a090-9e489b7547c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cor Condicional Horas Devidas' = ```
			
			VAR _SelecaoParametro = SELECTEDVALUE( aux_SlicerY[Parameter Order] )
			VAR _Switch = 
			SWITCH(
			    TRUE(), 
			    _SelecaoParametro = 0, "#FF0000",
			    _SelecaoParametro = 1, "#007A0A"
			)
			RETURN
			_Switch
			```
		lineageTag: 57458c12-046a-4793-b477-e9645ac1a7dd

	column Column
		isHidden
		formatString: 0
		lineageTag: 4c634a75-6995-48cd-a494-7490b4792572
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = d5950f6bcf084abb9f914fe44159ea1f

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

